# Generated by Django 5.2.17 on 2026-10-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('event_type', models.CharField(choices=[('bible-study', 'Bible Study'), ('discussion', 'Discussion'), ('retreat', 'Retreat'), ('worship', 'Worship Service'), ('fellowship', 'Fellowship'), ('other', 'Other')], default='other', max_length=30)),
                ('date', models.DateField()),
                ('time', models.CharField(blank=True, max_length=80)),
                ('mode', models.CharField(default='Online', max_length=30)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('registration_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=160)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('is_published', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='Faith Alone Saves', max_length=120)),
                ('tagline', models.CharField(default='LOVE IN FELLOWSHIP & TRUTH', max_length=160)),
                ('hero_title', models.CharField(default='Growing together in Christ.', max_length=180)),
                ('hero_intro', models.TextField(default="Equipping campus students to grow in God's Word, use their spiritual gifts, and selflessly impact their campuses.")),
                ('vision', models.TextField(default='To equip campus students wholistically—grounding them in God’s Word, helping them worship and exercise their spiritual gifts, and inspiring them to selflessly expand God’s Kingdom.')),
                ('mission', models.TextField(default="Connecting students through online meetings, in-person gatherings, and retreats; nurturing them wholistically through God's Word and mentorship; and creating opportunities for them to use their spiritual gifts to lead, serve, and selflessly impact their campuses.")),
                ('whatsapp_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tuesday_time', models.CharField(default='Every Tuesday • 7:00 PM', max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=120)),
                ('college', models.CharField(blank=True, max_length=160)),
                ('testimony', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonies/')),
                ('is_approved', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
