# Generated by Django 5.2.17 on 2026-10-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('poster', 'Poster'), ('highlight', 'Highlight'), ('update', 'Update'), ('event', 'Event'), ('announcement', 'Announcement')], default='update', max_length=30)),
                ('image', models.ImageField(upload_to='homepage-slides/')),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, max_length=80)),
                ('button_url', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tuesday_time',
            field=models.CharField(default='Every Tuesday - 7:00 PM', max_length=80),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vision',
            field=models.TextField(default="To equip campus students wholistically - grounding them in God's Word, helping them worship and exercise their spiritual gifts, and inspiring them to selflessly expand God's Kingdom."),
        ),
    ]
