# Generated by Django 5.2.17 on 2026-10-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_homepageslide_alter_sitesettings_tuesday_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('author', models.CharField(default='FAS', max_length=120)),
                ('category', models.CharField(choices=[('bible-study', 'Bible Study'), ('christian-life', 'Christian Life'), ('student-life', 'Student Life'), ('faith', 'Faith'), ('testimony', 'Testimony'), ('fas-updates', 'FAS Updates'), ('other', 'Other')], default='other', max_length=30)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/')),
                ('excerpt', models.TextField(blank=True, max_length=400)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
