# Generated by Django 5.2.17 on 2026-10-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SermonPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('speaker', models.CharField(default='FAS', max_length=120)),
                ('category', models.CharField(choices=[('bible-study', 'Bible Study'), ('sermon', 'Sermon'), ('devotional', 'Devotional'), ('worship', 'Worship'), ('conference', 'Conference'), ('other', 'Other')], default='sermon', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('pdf_file', models.FileField(upload_to='sermons/pdfs/')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
