# Generated by Django 5.2.17 on 2026-10-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_sermonpdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='FASVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('speaker', models.CharField(default='FAS', max_length=120)),
                ('category', models.CharField(choices=[('bible-study', 'Bible Study'), ('sermon', 'Sermon'), ('worship', 'Worship'), ('testimony', 'Testimony'), ('retreat', 'Retreat'), ('fas-updates', 'FAS Updates'), ('other', 'Other')], default='other', max_length=30)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/')),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
