# Generated by Django 5.2.17 on 2026-10-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_fasvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(default='FAS', max_length=120)),
                ('category', models.CharField(choices=[('bible-study', 'Bible Study'), ('christian-life', 'Christian Life'), ('student-life', 'Student Life'), ('devotional', 'Devotional'), ('faith', 'Faith'), ('testimony', 'Testimony'), ('other', 'Other')], default='other', max_length=30)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='ebooks/covers/')),
                ('description', models.TextField(blank=True)),
                ('ebook_file', models.FileField(upload_to='ebooks/files/')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
