# Generated by Django 5.2.17 on 2026-10-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_ebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('retreats', 'Retreats'), ('events', 'FAS Events'), ('camps-conferences', 'Camps & Conferences'), ('cottage-prayer', 'Cottage Prayer & Fellowship'), ('bible-study', 'Bible Study'), ('worship-prayer', 'Worship & Prayer'), ('outreach-mission', 'Outreach & Mission'), ('fellowship-gatherings', 'Fellowship & Gatherings')], default='events', max_length=40),
        ),
    ]
