# Generated by Django 5.2.17 on 2026-10-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_galleryimage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermonpdf',
            name='pdf_file',
            field=models.FileField(storage='cloudinary_storage.storage.RawMediaCloudinaryStorage', upload_to='sermons/pdfs/'),
        ),
    ]
