# Generated by Django 5.2.17 on 2026-10-03 02:00

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_fix_cloudinary_media_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermonpdf',
            name='pdf_file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='sermons/pdfs/'),
        ),
    ]
