# Generated by Django 5.2.17 on 2026-10-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_sermonpdf_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_read',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='request_type',
            field=models.CharField(choices=[('prayer', 'Prayer Request'), ('message', 'Message')], default='message', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('responded', 'Responded'), ('archived', 'Archived')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(max_length=5000),
        ),
    ]
