# Generated by Django 5.2.17 on 2026-10-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_remove_contactmessage_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
