# Generated by Django 5.2.17 on 2026-10-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_contactmessage_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='impact_statement',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
